language: rust
rust:
  - nightly
script:
  - cargo build --verbose
  - cargo test --package command-macros-plugin --verbose
  - cargo test -Z package-features --features nightly --package command-macros --verbose
cache: cargo
